In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
l = [1,2,3,4,5]
arr = np.array(l)
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
p = [1,2,3,4,"ajay"]
brr = np.array(p)

print(brr)

['1' '2' '3' '4' 'ajay']


In [10]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Print the array
print("Array:")
print(arr)

# Key Properties
print("\nKey Properties:")
print("Dimensions (ndim):", arr.ndim)     # 2
print("Shape:", arr.shape)                # (2, 3)
print("Size:", arr.size)                  # 6
print("Data type:", arr.dtype)            # int64 or int32

# Accessing Elements
print("\nAccessing Elements:")
print("Element at [0,1]:", arr[0, 1])     # 2
print("Second row:", arr[1, :])           # [4 5 6]
print("Third column:", arr[:, 2])         # [3 6])


Array:
[[1 2 3]
 [4 5 6]]

Key Properties:
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Data type: int32

Accessing Elements:
Element at [0,1]: 2
Second row: [4 5 6]
Third column: [3 6]


In [12]:
# more way to convert array :
l1 = [1,2,3,4,5]
arr2 = np.asanyarray(l1)
print(arr2)
print(type(arr2))


l3 = [1,2,3,4,5]
arr3 = np.asanyarray(l3)
print(arr3)
print(type(arr3))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
"""
NOTE: asanyarray will convert the input to an array but if something is already in anrray it will not be able to convert but pass ndarray subclass through
 therefore if something is already in array or part of array it will simpally allow to pass through it 
"""     
np.asanyarray(arr3)

array([1, 2, 3, 4, 5])

In [ ]:
""" shallow copy """

l = [1,2,3,4,5]
arr = np.array(l)
print(f"arr: {arr}")

brr = arr # brr and arr will point to the same memory location, any changes done to 'arr' or 'brr'  will also reflect on other.
print("brr:", brr)

arr[0] = 100

print(f" arr: {arr},     brr: {brr}")


arr: [1 2 3 4 5]
brr: [1 2 3 4 5]
 arr: [100   2   3   4   5],     brr: [100   2   3   4   5]


In [16]:
"""deep copy"""
crr = arr.copy()
print(f"crr: {crr}")

arr[1] = 200
crr[2] = 300
print(f"arr: {arr}")
print(f"brr: {brr}")
print(f"crr:{crr}")

crr: [100   2   3   4   5]
arr: [100 200   3   4   5]
brr: [100 200   3   4   5]
crr:[100   2 300   4   5]


In [17]:
"""Creating array from np.fromfunction()"""
arr = np.fromfunction(lambda i,j: i==j, (3,3))
print(f"arr: {arr}")
print(arr.ndim)
print(arr.size)
print(arr.shape)

arr: [[ True False False]
 [False  True False]
 [False False  True]]
2
9
(3, 3)


In [19]:
# Function that just returns row + col
def func(i, j):
    return i + j

arr = np.fromfunction(func, (3, 3), dtype=int)
print(f"arr: {arr}")


arr: [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [27]:
import numpy as np

# np.fromstring() converts a string into a 1D NumPy array.
# Arguments:
#  - The first argument is the input string.
#  - sep specifies how values in the string are separated (delimiter).

d = np.fromstring("22 23 24", sep=" ")

# Print the array
print(d)


[22. 23. 24.]


In [28]:
import numpy as np

# Define a string
string = "Ajay, Vijay, Sanjay"

# Use Python's split() method to break the string into parts
# split(",") means "split wherever a comma occurs"
parts = string.split(",")

# Convert the resulting Python list into a NumPy array
crr = np.array(parts)

# Print the NumPy array
print(crr)


['Ajay' ' Vijay' ' Sanjay']
