In [6]:
import numpy as np

arr = np.zeros(5)
print(f"arr(by default : {arr})")

brr = np.zeros(10, dtype= int)
print(f"brr:(int): {brr}")
crr = np.zeros((3,4))
print(f"crr(two dimensional): {crr}")



arr(by default : [0. 0. 0. 0. 0.])
brr:(int): [0 0 0 0 0 0 0 0 0 0]
crr(two dimensional): [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:

arr = np.ones(5)
print(f"arr(by default : {arr})")

brr = np.ones(10, dtype= int)
print(f"brr:(int): {brr}")
crr = np.ones((3,4))
print(f"crr(two dimensional): {crr}")

arr(by default : [1. 1. 1. 1. 1.])
brr:(int): [1 1 1 1 1 1 1 1 1 1]
crr(two dimensional): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr = np.zeros((3,4))
print(arr)
print("\n")

arr = arr+5 
print(arr)

print("\n")
arr = arr*2
print(arr)

# similartly we can do substract

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [10]:
#Identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# .empty()
np.empty((2,3))

array([[3.47739925e-081, 1.60561411e-051, 6.53734410e-042],
       [1.84628513e+184, 6.94088324e+169, 7.56571287e-307]])

In [15]:
# Random Module : 
import random
random.choice((1,2,3,4,5,6))

6

In [16]:
random.choice("string")

'i'

In [18]:
random.randrange(1,8)

3

In [23]:
lst = [1,2,3,4,5,6,7]
random.shuffle(lst)
print(lst)

[3, 1, 4, 7, 2, 5, 6]


In [32]:
# Use of random() in numpy 
a =np.random.random_sample()
print(a)

b = np.random.random_sample((5,))
print(b)
print(np.random.rand(1))
print("\n")

print(f"2d arrya : {np.random.rand(2,3)}")

0.27455387035359646
[0.70124676 0.33169997 0.52676241 0.6253429  0.17092306]
[0.18212654]


2d arrya : [[0.97250414 0.69131574 0.72627592]
 [0.41949538 0.57191632 0.44401274]]


In [1]:
import numpy as np

np.random.randn(2,3)

array([[-1.42802769, -2.10291759,  0.11237285],
       [-1.2112536 , -1.06196283, -1.76476603]])

In [3]:
# np.random.randint(low, high=None, size=None, dtype=int)
arr = np.random.randint(1, 10, size=(2,3))
print(arr)

[[4 7 3]
 [8 8 6]]


In [7]:
# arrray.reshape() : It is used to change the shape of an array without changing its data.
arr = np.random.randint(1,10, size = (3,4))
print(f"original array : \n {arr}")
reshaped_arr = arr.reshape(2,6)
print(f"reshaped array : \n {reshaped_arr}")

# let say you don't know the number of rows or no of columns you can use -1
reshaped_arr = arr.reshape(-1,2)
print(f"reshaped array : \n {reshaped_arr}")

# we can use any number of dimentions 
reshaped_arr = arr.reshape(2,2,3)
print(f"reshaped array : \n {reshaped_arr}")

original array : 
 [[2 5 4 1]
 [3 5 5 1]
 [8 6 9 8]]
reshaped array : 
 [[2 5 4 1 3 5]
 [5 1 8 6 9 8]]
reshaped array : 
 [[2 5]
 [4 1]
 [3 5]
 [5 1]
 [8 6]
 [9 8]]
reshaped array : 
 [[[2 5 4]
  [1 3 5]]

 [[5 1 8]
  [6 9 8]]]


In [ ]:
arr = np.random.randint(1,10, size = (5,6))
print(f"oringinal array : \n {arr}")

#Conditions on array : 
condition = arr > 5
print(f"condition : \n {condition}")

arr2 = arr[condition] # arr2 = arr[arr > 5] select all the element of arr which are greater than 5
print(f"arr2 : \n {arr2}")

print(f"\naccessing the element of array ")
print(arr[0])
print(arr[1])

# array slicing : 
sliced_arr = arr[1:4, 2:5] # selecting rows from 1 to 3 and columns from 2 to 4
print(f"sliced array : \n {sliced_arr}")


brr = arr[0:3, [0,2]]
print(f"brr: \n {brr}")

crr = arr[0, [2,3]]
print(f"crr : \n {crr}")

oringinal array : 
 [[2 9 6 2 1 9]
 [3 3 4 5 7 6]
 [8 5 6 1 8 1]
 [5 9 7 8 9 9]
 [4 6 3 2 1 5]]
condition : 
 [[False  True  True False False  True]
 [False False False False  True  True]
 [ True False  True False  True False]
 [False  True  True  True  True  True]
 [False  True False False False False]]
arr2 : 
 [9 6 9 7 6 8 6 8 9 7 8 9 9 6]

accessing the element of array 
[2 9 6 2 1 9]
[3 3 4 5 7 6]
sliced array : 
 [[4 5 7]
 [6 1 8]
 [7 8 9]]
brr: 
 [[2 6]
 [3 4]
 [8 6]]
crr : 
 [6 2]


In [21]:
arr1 = np.random.randint(1,10, size = (3,3))
arr2 = np.random.randint(1,10, size = (3,3))
print(f"arr1 : \n {arr1}")
print(f"arr2 : \n {arr2}")

# index wise multiplication
multiplied_arr = arr1 * arr2
print(f"multiplied_arr : \n {multiplied_arr}")

# matrix multiplication
matrix_multiplication = np.dot(arr1, arr2)
print(f"matrix_multiplication : \n {matrix_multiplication}")

arr1 : 
 [[6 2 7]
 [6 1 4]
 [6 8 7]]
arr2 : 
 [[9 5 4]
 [8 8 2]
 [2 6 7]]
multiplied_arr : 
 [[54 10 28]
 [48  8  8]
 [12 48 49]]
matrix_multiplication : 
 [[ 84  88  77]
 [ 70  62  54]
 [132 136  89]]


In [23]:
# flattening the array
arr = np.random.randint(1,10, size=(3,4))
print(f"original array : \n {arr}")
flattened_arr = arr.flatten()
print(f"flattened array : \n {flattened_arr}")

original array : 
 [[7 5 2 3]
 [9 4 4 6]
 [4 8 1 6]]
flattened array : 
 [7 5 2 3 9 4 4 6 4 8 1 6]


In [30]:
#np.expand_dims()
# increase the dimention by 1 in the prviede axis, 0 means row(x axis), and one means column(y axis)
arr = np.array([1,2,3,4])
print(arr)


brr = np.expand_dims(arr, axis=0)
print(f"brr : \n {brr}")
print(brr.ndim)

crr = np.expand_dims(arr, axis=1)
print(f"crr : \n {crr}")
print(crr.ndim)


#--------Lets do this for 2d array
print("\n2D array\n")
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

brr = np.expand_dims(arr, axis=0)
print(f"brr : \n {brr}")
print(brr.ndim)

crr = np.expand_dims(arr, axis=1)
print(f"crr : \n {crr}")
print(crr.ndim)


[1 2 3 4]
brr : 
 [[1 2 3 4]]
2
crr : 
 [[1]
 [2]
 [3]
 [4]]
2

2D array

[[1 2 3]
 [4 5 6]]
2
brr : 
 [[[1 2 3]
  [4 5 6]]]
3
crr : 
 [[[1 2 3]]

 [[4 5 6]]]
3


In [32]:
# np.squeeze() : opposite of expand_dims, it removes the axis which has only one element
arr = np.array([[[1,2,3,4]]])
print(arr)
print(arr.ndim)

squeezed_arr = np.squeeze(arr)
print(f"squeezed_arr : \n {squeezed_arr}")
print(squeezed_arr.ndim)

[[[1 2 3 4]]]
3
squeezed_arr : 
 [1 2 3 4]
1


In [1]:
import numpy as np

# 1. Repeat elements in a 1D array (scalar repeat)
arr1 = np.array([1, 2, 3])
print("Repeat each element twice:\n", np.repeat(arr1, 2))
# [1 1 2 2 3 3]

# 2. Different repeat counts per element
print("\nDifferent repeat counts:\n", np.repeat(arr1, [1, 2, 3]))
# [1 2 2 3 3 3]

# 3. Repeat in a 2D array without axis (flattens first)
arr2 = np.array([[1, 2],
                 [3, 4]])
print("\nRepeat each element twice (flattened):\n", np.repeat(arr2, 2))
# [1 1 2 2 3 3 4 4]

# 4. Repeat along columns (axis=1)
print("\nRepeat along columns (axis=1):\n", np.repeat(arr2, 2, axis=1))
# [[1 1 2 2]
#  [3 3 4 4]]

# 5. Repeat along rows (axis=0)
print("\nRepeat along rows (axis=0):\n", np.repeat(arr2, 2, axis=0))
# [[1 2]
#  [1 2]
#  [3 4]
#  [3 4]]


Repeat each element twice:
 [1 1 2 2 3 3]

Different repeat counts:
 [1 2 2 3 3 3]

Repeat each element twice (flattened):
 [1 1 2 2 3 3 4 4]

Repeat along columns (axis=1):
 [[1 1 2 2]
 [3 3 4 4]]

Repeat along rows (axis=0):
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [5]:
import numpy as np

# -------------------------------
# 1D ARRAY EXAMPLES
# -------------------------------
arr1d = np.array([1, 2, 3, 4, 5])

print("Original 1D array:\n", arr1d)

# Positive shift
print("\nRoll 1D (+2):\n", np.roll(arr1d, 2))

# Negative shift
print("\nRoll 1D (-2):\n", np.roll(arr1d, -2))


# -------------------------------
# 2D ARRAY EXAMPLES
# -------------------------------
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("\nOriginal 2D array:\n", arr2d)

# Case 1: No axis (flatten + roll)
print("\nRoll 2D (no axis, +2):\n", np.roll(arr2d, 2))
print("\nRoll 2D (no axis, -2):\n", np.roll(arr2d, -2))

# Case 2: Axis=0 (vertical shift)
print("\nRoll 2D axis=0 (+1 down):\n", np.roll(arr2d, 1, axis=0))
print("\nRoll 2D axis=0 (-1 up):\n", np.roll(arr2d, -1, axis=0))

# Case 3: Axis=1 (horizontal shift)
print("\nRoll 2D axis=1 (+1 right):\n", np.roll(arr2d, 1, axis=1))
print("\nRoll 2D axis=1 (-1 left):\n", np.roll(arr2d, -1, axis=1))

# Case 4: Multiple axes
print("\nRoll 2D (shift=(+1 row, -1 col)):\n", np.roll(arr2d, shift=(1, -1), axis=(0, 1)))


Original 1D array:
 [1 2 3 4 5]

Roll 1D (+2):
 [4 5 1 2 3]

Roll 1D (-2):
 [3 4 5 1 2]

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Roll 2D (no axis, +2):
 [[8 9 1]
 [2 3 4]
 [5 6 7]]

Roll 2D (no axis, -2):
 [[3 4 5]
 [6 7 8]
 [9 1 2]]

Roll 2D axis=0 (+1 down):
 [[7 8 9]
 [1 2 3]
 [4 5 6]]

Roll 2D axis=0 (-1 up):
 [[4 5 6]
 [7 8 9]
 [1 2 3]]

Roll 2D axis=1 (+1 right):
 [[3 1 2]
 [6 4 5]
 [9 7 8]]

Roll 2D axis=1 (-1 left):
 [[2 3 1]
 [5 6 4]
 [8 9 7]]

Roll 2D (shift=(+1 row, -1 col)):
 [[8 9 7]
 [2 3 1]
 [5 6 4]]


Operation on numpy string 

In [9]:
str_arr = np.array(['apple', 'banana', 'cherry'])
print(f"str_array : {str_arr}")
#uppercase : 
print("upper_case: ",np.char.upper(str_arr))
# to print first letter capital
print("first letter capital: ",np.char.capitalize(str_arr))
# to print first letter small   
print("first letter small: ",np.char.lower(str_arr))

str_array : ['apple' 'banana' 'cherry']
upper_case:  ['APPLE' 'BANANA' 'CHERRY']
first letter capital:  ['Apple' 'Banana' 'Cherry']
first letter small:  ['apple' 'banana' 'cherry']


Mathimatical operation

In [10]:
arr = np.random.randint(1,10, size = (3,3))
print(f"original array : \n {arr}")

#square root of each element
sqrt_arr = np.sqrt(arr)
print(f"square root of each element : \n {sqrt_arr}")

#sin of array 
sin_arr = np.sin(arr)
print(f"sin of each element : \n {sin_arr}")

#log value of each element
log_arr = np.log(arr)
print(f"log value of each element : \n {log_arr}")

#exp value of each element
exp_arr = np.exp(arr)
print(f"exp value of each element : \n {exp_arr}")

#power of each element
power_arr = np.power(arr, 2)
print(f"power of each element : \n {power_arr}")

# to get the maximum value from array
max_value = np.max(arr)
print(f"maximum value from array : {max_value}")

#average value of array
avg_value = np.mean(arr)
print(f"average value of array : {avg_value}")

# standard deviation of array
std_value = np.std(arr)
print(f"standard deviation of array : {std_value}")

# variance of array 
variance_val = np.var(arr)
print(f"variance of array : {variance_val}")

original array : 
 [[8 8 2]
 [2 9 8]
 [2 9 5]]
square root of each element : 
 [[2.82842712 2.82842712 1.41421356]
 [1.41421356 3.         2.82842712]
 [1.41421356 3.         2.23606798]]
sin of each element : 
 [[ 0.98935825  0.98935825  0.90929743]
 [ 0.90929743  0.41211849  0.98935825]
 [ 0.90929743  0.41211849 -0.95892427]]
log value of each element : 
 [[2.07944154 2.07944154 0.69314718]
 [0.69314718 2.19722458 2.07944154]
 [0.69314718 2.19722458 1.60943791]]
exp value of each element : 
 [[2.98095799e+03 2.98095799e+03 7.38905610e+00]
 [7.38905610e+00 8.10308393e+03 2.98095799e+03]
 [7.38905610e+00 8.10308393e+03 1.48413159e+02]]
power of each element : 
 [[64 64  4]
 [ 4 81 64]
 [ 4 81 25]]
maximum value from array : 9
average value of array : 5.888888888888889
standard deviation of array : 2.960647243216495
variance of array : 8.765432098765432


Sorting and Searching in Numpy array 

In [14]:
arr = np.array([1,89,37,20,90,-1])
print(f"oringinal array : \n {arr}")

# sorting the array
sorted_arr = np.sort(arr)
print(f"sorted array : \n {sorted_arr}")

# searchsorted array : It returns the index where the element should be inserted to maintain order.
idx = np.searchsorted(sorted_arr, 40)
print(f"index where 40 should be inserted to maintain order : {idx}")

# count non-zero elements in the array 
brr = np.array([1,0,3,0,5,6,0])
non_zero_count = np.count_nonzero(brr)
print(f"number of non-zero elements in brr : {non_zero_count}")

# we can also use where to find non-zero elements
non_zero_indices = np.where(brr != 0) # brr > 0 also works
print(f"indices of non-zero elements in brr : {non_zero_indices}")

# extract : Extract elements that satisfy a condition
extracted_elements = np.extract(brr > 0, brr) # brr != 0 also works 
print(f"extracted elements from brr : {extracted_elements}")

oringinal array : 
 [ 1 89 37 20 90 -1]
sorted array : 
 [-1  1 20 37 89 90]
index where 40 should be inserted to maintain order : 4
number of non-zero elements in brr : 4
indices of non-zero elements in brr : (array([0, 2, 4, 5], dtype=int64),)
extracted elements from brr : [1 3 5 6]


In [17]:
# find the determinant of a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
determinant = np.linalg.det(matrix)  # linear algebra module
print(f"determinant of the matrix : {determinant}")


# inverse of a matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print(f"inverse of the matrix : \n {inverse_matrix}")
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

determinant of the matrix : 0.0
Matrix is singular and cannot be inverted.


In [20]:
# solving linear equations using linear algebra
# Example: Solve the system of equations
# 2x + 3y + z = 1
# 4x + y + 2z = 2
# 3x + 2y + 3z = 3

# converting the coefficients into matrix form
A = np.array([[2, 3, 1],
              [4, 1, 2],
               [3, 2, 3]])
B = np.array([1, 2, 3]) # constants on the right side

# solving for [x, y, z]
solution = np.linalg.solve(A, B)
print(f"solution of the linear equations [x, y, z] : {solution}")

solution of the linear equations [x, y, z] : [0. 0. 1.]
